print("shamsa kanwal")
print("shamsa \" kanwal")
print("shamsa\n kanwal")
name_person= "fatima"
print(name_person + " is 50 years old, she is a grand mother, but she is happy to be")
name_person= "shafaq"
print(name_person +" lecturer in university ")
print (name_person + " have to go outside the town")
sentence = "PAKISTAN ZINDABAAD"
sentence= ("shafaq is very hardworking")
print(sentence)
print(sentence.lower())
print(name_person.upper())
print(sentence.isupper())
print(name_person.islower())
print(name_person.upper().islower())
print(len(name_person))
print(len(sentence))
print(sentence[5])
print(name_person.index("a"))
print (sentence.lower().islower())
print(sentence.replace("shafaq","shamsa"))
print(4 +(3-4))
num= 5
print(num)
print(str(num) + " is lucky number")
print(pow(5,6))
print(max(-5 ,0 ,1))
num1= input("enter num1:")
num2= input("enter num2")
result= int (num1) + int (num2)
print(result)
name= input ("your name:")
age = input ("your age:")
print (name + " is beautifull name" + age + " too young you are")
print(4 + 5)
print(num)
sg= ("sadaf, hina")
print(sg)
print (sg.replace("sadaf","hina"))
colour= input("enter colour:")
plural_noun=input("enter plural noun:")
celebrity=input("enter Celebrity name:")
print(colour + " is attractive")
print(celebrity + " has good personality")
print(plural_noun + " are " + colour)



